### ISSUE TITLE
大佬好。。cunhua 好像收费了？？

### ISSUE THREAD

**Issue by joekleenubuntu** [xirenxianngmu/z#3]
非VIP会员无法浏览帖子。。

之前一直用大佬的签到脚本。。刚输入账号密码，提示不能登录。 然后。。试着原用户名注册了一下。。发现可以注册。。

估计我被删号了。

不知道大佬还有什么类似的论坛下载资源呢？

感谢

**Comment by ziyonglixian** [comment]
我这边好像没出现这个问题，另外以防万一之前那个ku删掉吧，保留这个fork就行，之前那个ku GitHub这边怀疑挖矿所以我删了，最近actions这边不太平

**Comment by joekleenubuntu** [comment]
ku已删。 cunhua收费的问题我知道了。。是我上了假的网站。。哈哈哈  。谢谢大佬

**Comment by ziyonglixian** [comment]
> ku已删。 cunhua收费的问题我知道了。。是我上了假的网站。。哈哈哈 。谢谢大佬

23333，没事
